name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'   # 每小时检查一次
  workflow_dispatch:      # 可手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/langgenius/dify.git || true
          git fetch upstream
          git checkout main
          git merge upstream/main || true

      - name: Push changes
        run: |
          git push origin main
